"""Generated MicroPython dataclass field metadata. Do not edit by hand."""

IDENTITY_MODE = "qualified_name"

FIELD_MANIFEST = {
    ('app.combat.arcane', 'ArcaneDischarge'): ('spell_bonus_percent', 'broken_target', 'break_reduction_percent', 'instability_was_active'),
    ('app.combat.arcane', 'GravemantleRules'): ('overcharge_bonus_percent', 'break_mitigation_reduction_percent', 'backlash_chance_percent', 'backlash_damage_min', 'backlash_damage_max', 'instability_vulnerability_percent'),
    ('app.combat.brace', 'BraceRules'): ('incoming_reduction_percent', 'follow_up_damage_bonus_percent', 'follow_up_mechanic'),
    ('app.combat.combat_state', '_ArcaneChargeState'): ('owner', 'broken_target', 'instability_active'),
    ('app.combat.combat_state', '_BraceState'): ('owner', 'incoming_protection_active', 'incoming_reduction_percent', 'heavy_payoff_active', 'heavy_payoff_damage_bonus_percent'),
    ('app.combat.combat_state', '_HealCooldown'): ('owner', 'remaining_actions'),
    ('app.combat.frost', 'FrostRules'): ('frostbite_damage_per_tick', 'frostbite_duration_ticks', 'mournglass_backlash_chance_percent'),
    ('app.combat.move', 'Move'): ('name', 'kind', 'resource_type', 'resource_cost', 'power', 'scales_with', 'accuracy', 'target', 'damage_type', 'mechanic', 'description', 'presentation', 'is_spell', 'frost_backlash'),
    ('app.combat.move_presentation', 'MovePresentation'): ('role', 'affinity_label', 'static_summary'),
    ('app.combat.result', 'CombatOutcome'): ('outcome_type', 'amount', 'target', 'charge_count'),
    ('app.combat.result', 'MoveResult'): ('accepted', 'hit', 'move_name', 'resource_spent', 'damage', 'healing', 'statuses_applied', 'reason', 'critical', 'outcomes'),
    ('app.combat.status_state', 'BurnStatus'): ('source', 'target', 'remaining_ticks', 'damage_per_tick'),
    ('app.combat.status_state', 'ConductiveStatus'): ('source', 'target'),
    ('app.combat.status_state', 'FrostCharge'): ('source', 'target', 'charge_count'),
    ('app.combat.status_state', 'FrostbiteStatus'): ('source', 'target', 'remaining_ticks', 'damage_per_tick'),
    ('app.combat.status_state', 'FrozenStatus'): ('source', 'target'),
    ('app.combat.status_state', 'PoisonStatus'): ('source', 'target', 'remaining_ticks', 'damage_per_tick'),
    ('app.combat.status_state', 'StunStatus'): ('source', 'target'),
    ('app.combat.status_state', 'TurbulenceStatus'): ('source', 'target'),
    ('app.combat.storm', 'StormRules'): ('conductive_damage_bonus_percent', 'turbulence_damage_bonus_percent', 'lightning_storm_damage_bonus_percent', 'stun_chance_percent'),
    ('app.content.drifter_spec', 'ClassMechanicSpec'): ('name', 'description'),
    ('app.content.drifter_spec', 'DrifterSpec'): ('drifter_id', 'choice', 'archetype_name', 'stats', 'combat_moves', 'class_mechanic', 'starting_weapon_id', 'short_name', 'display_name', 'ascii_art', 'origin_title', 'biography', 'dungeon_motive', 'combat_role', 'combat_summary', 'strengths', 'weaknesses', 'weapon', 'discipline', 'quote', 'selection_summary', 'starting_run_inventory', 'starting_prepared_payloads'),
    ('app.content.drifter_spec', 'DrifterStatSpec'): ('constitution', 'spirit', 'intelligence', 'strength', 'dexterity', 'intuition'),
    ('app.content.encounter_spec', 'EncounterSpec'): ('encounter_id', 'enemy_archetype_ids'),
    ('app.content.enemy_spec', 'EnemySpec'): ('archetype_id', 'name', 'stats', 'hp', 'mana', 'exp_reward', 'gold_reward', 'rank', 'role', 'behavior', 'capabilities', 'moves', 'supported_tiers'),
    ('app.content.enemy_spec', 'StatBlockSpec'): ('constitution', 'spirit', 'intelligence', 'strength', 'dexterity', 'intuition'),
    ('app.content.route_spec', 'RouteNodeSpec'): ('node_id', 'display_label', 'kind', 'encounter_id'),
    ('app.content.route_spec', 'RouteSpec'): ('route_id', 'nodes'),
    ('app.content.weapon_spec', 'WeaponSpec'): ('item_id', 'persistence_key', 'name', 'weapon_type', 'intended_wielder', 'stat_bonuses', 'value', 'description'),
    ('app.game.save_repository', 'SaveLoadResult'): ('status', 'game_state', 'error', 'migrated_from_schema_7'),
    ('app.player.character_run_state', 'CharacterRunCheckpoint'): ('inventory', 'prepared_payloads'),
    ('app.player.inventory_action', 'InventoryActionResult'): ('action_id', 'accepted', 'reason', 'outcomes'),
    ('app.player.player_state', 'PlayerBattleCheckpoint'): ('health_current', 'mana_current', 'super_current', 'character_run_state'),
    ('app.player.run_items', 'InventoryRecipeDefinition'): ('action_id', 'ingredient_ids', 'result_display_name', 'infusion_kind'),
    ('app.player.run_items', 'RunItemDefinition'): ('item_id', 'display_name', 'description', 'commands'),
    ('app.presentation.battle_models', 'ActionOptionView'): ('intent', 'number', 'label', 'enabled', 'disabled_reason'),
    ('app.presentation.battle_models', 'BattleLogEntry'): ('event_type', 'actor_name', 'target_name', 'action_name', 'accepted', 'hit', 'amount', 'critical', 'resource_spent', 'statuses_applied', 'reason', 'rejection_reason', 'outcomes'),
    ('app.presentation.battle_models', 'BattleView'): ('interaction_phase', 'player', 'enemies', 'super_meter', 'encounter_label', 'action_options', 'move_options', 'target_options', 'inventory_items', 'selected_inventory_item', 'inventory_commands', 'inventory_inspection', 'inventory_companions', 'inventory_confirmation', 'log_entries', 'visual'),
    ('app.presentation.battle_models', 'BattleVisualView'): ('player_lines', 'enemy_lines'),
    ('app.presentation.battle_models', 'CombatantView'): ('display_name', 'hp_current', 'hp_maximum', 'mana_current', 'mana_maximum', 'super_current', 'super_maximum', 'defending', 'temporary_labels'),
    ('app.presentation.battle_models', 'EnemyCombatantView'): ('target_id', 'display_label', 'hp_current', 'hp_maximum', 'mana_current', 'mana_maximum', 'super_current', 'super_maximum', 'defending', 'temporary_labels', 'defeated'),
    ('app.presentation.battle_models', 'InventoryCommandOptionView'): ('command', 'number', 'label', 'enabled', 'disabled_reason'),
    ('app.presentation.battle_models', 'InventoryConfirmationView'): ('source_item_id', 'source_display_name', 'companion_item_id', 'companion_display_name', 'action_id', 'result_display_name'),
    ('app.presentation.battle_models', 'InventoryInspectionView'): ('item_id', 'display_name', 'description'),
    ('app.presentation.battle_models', 'InventoryItemOptionView'): ('item_id', 'number', 'display_name', 'quantity', 'enabled', 'disabled_reason'),
    ('app.presentation.battle_models', 'MoveOptionView'): ('selection_key', 'number', 'name', 'tags', 'rules_summary', 'resource_label', 'enabled', 'disabled_reason'),
    ('app.presentation.battle_models', 'SuperMeterView'): ('current', 'maximum', 'fill_bps', 'ready', 'activation_key', 'activation_offered'),
    ('app.presentation.battle_models', 'TargetOptionView'): ('target_id', 'number', 'display_label', 'hp_current', 'hp_maximum', 'temporary_labels', 'move_preview', 'enabled', 'disabled_reason'),
    ('app.presentation.overworld_models', 'AccessorySlotView'): ('label', 'item_name'),
    ('app.presentation.overworld_models', 'CharacterOverviewView'): ('display_name', 'archetype_label', 'stats', 'level', 'exp_current', 'exp_threshold', 'exp_fill_bps', 'hp_current', 'hp_maximum', 'mana_current', 'mana_maximum', 'super_current', 'super_maximum'),
    ('app.presentation.overworld_models', 'EquipmentView'): ('necklace', 'ring', 'benefits'),
    ('app.presentation.overworld_models', 'InventoryView'): ('items', 'selected_item_key', 'inspected_item'),
    ('app.presentation.overworld_models', 'MapEncounterInspectionView'): ('encounter_label', 'composition', 'boss'),
    ('app.presentation.overworld_models', 'MapNodeView'): ('display_label', 'kind_label', 'state'),
    ('app.presentation.overworld_models', 'MapView'): ('nodes',),
    ('app.presentation.overworld_models', 'OverworldItemView'): ('selection_key', 'display_name', 'quantity', 'description', 'overworld_use_enabled'),
    ('app.presentation.overworld_models', 'OverworldOptionView'): ('action', 'label', 'enabled', 'disabled_reason'),
    ('app.presentation.overworld_models', 'OverworldView'): ('screen', 'location_label', 'adventure_text', 'options', 'contextual_route_option', 'notice', 'character', 'skills', 'weapon', 'equipment', 'inventory', 'route_map', 'encounter_inspection'),
    ('app.presentation.overworld_models', 'SkillMoveView'): ('name', 'description'),
    ('app.presentation.overworld_models', 'SkillsView'): ('growth_points_available', 'growth_message', 'stats', 'moves'),
    ('app.presentation.overworld_models', 'StatBonusView'): ('label', 'amount'),
    ('app.presentation.overworld_models', 'StatRowView'): ('stat_name', 'label', 'value', 'increase_visible', 'increase_enabled', 'disabled_reason'),
    ('app.presentation.overworld_models', 'WeaponView'): ('name', 'weapon_type', 'intended_wielder', 'bonuses', 'description'),
    ('app.ui.battle_ui', 'ChooseAction'): ('intent',),
    ('app.ui.battle_ui', 'ChooseInventoryCommand'): ('command',),
    ('app.ui.battle_ui', 'ChooseInventoryCompanion'): ('item_id',),
    ('app.ui.battle_ui', 'ChooseInventoryItem'): ('item_id',),
    ('app.ui.battle_ui', 'ChooseMove'): ('move_key',),
    ('app.ui.battle_ui', 'ChooseTarget'): ('target_id',),
    ('app.ui.battle_ui', 'ConfirmInventoryUse'): ('confirmed',),
    ('app.ui.battle_ui', 'GoBack'): (),
    ('app.ui.overworld_ui', 'ChooseOverworldAction'): ('action',),
    ('app.ui.overworld_ui', 'ChooseOverworldItem'): ('selection_key',),
    ('app.ui.overworld_ui', 'ChoosePermanentStatIncrease'): ('stat_name',),
}
